export const Products = [
    {
        id: 1,
        title: 'Steel Series Mouse',
        details: `Keep a tab on your daily activities with this tracker from GOQii. From your heart rate to your sleep patterns, this tracker helps you lead a healthy lifestyle by tracking your activities. You can also receive notifications from your phone on its large OLED display. Charging this device is easy, as it comes with an integrated USB charger, and it can run up to 7 days on a single full charge.`,
        category: ['Mouse', 'Electronics'],
        price: '1200',
        offer: '100',
        offerPrice: '1100',
        color: ['red', 'green', 'blue', 'yellow'],
        condition: 'New',
    },

    {
        id: 2,
        title: `boAt Rockerz 510 Super Extra Bass`,
        details: `Connect your smartphone to this headset using Bluetooth or a 3.5-mm auxiliary cable and get grooving. Packed with a 400-mAh battery, these Boat headphones offer a playback time of about 10 hours so that listening to your favourite tunes for hours on end is a piece of cake.`,
        category: ['Headphone', 'Electronics'],
        price: '2500',
        offer: '250',
        offerPrice: '2250',
        color: ['red', 'blue', 'yellow'],
        condition: 'New'
    },
    {
        id: 3,
        title: `Apple MacBook Air Core i5 8th Gen`,
        details: `The vision behind iMac has never wavered: Transform the desktop experience by fitting powerful, easy-to-use technology into an elegant, all-in-one design. The new iMac takes that idea to the next level — giving you even more amazing tools to do just about anything. iMac is packed with the latest processors, faster memory and phenomenal graphics. All coming to life on the brightest, most vibrant Retina display ever on a Mac. It’s the total package — powered up.`,
        category: ['Laptop', 'Electronics'],
        price: '120000',
        offer: '5000',
        offerPrice: '115000',
        color: ['gold', 'black', 'gray'],
        condition: 'New'
    },
    {
        id: 4,
        title: `Dragon War ELE-G11`,
        details: `Ergonomic Design for Professional Gamers to Give Extra Comfort, Braided Fiber Cable, Gold Plated USB Connector Provide Durability, Uses Sunplus Chipset, Customize the Devices Profile, Button Alignment, Performance and Speed, Capable of Pinpoint Tracking Precision Using Laser Beams of the Mouse and Attain Highest Scores in the Game, Can Use the Mouse on Any Surface without Any Performance Problems`,
        category: ['Mouse', 'Electronics'],
        price: '3200',
        offer: '500',
        offerPrice: '2700',
        color: ['gold', 'black', 'gray'],
        condition: 'New'
    },
    {
        id: 5,
        title: `Qwerty VR BOX Virtual Reality 3D Glasses`,
        details: `Good product!!!I am really happy with Flipkart!!!Soon i will review this amazing product on my channel and upload it(Search my channel named "R4Reviews" on youtube if you wanted to see my review).Thank you so much!!!`,
        category: ['Vr', 'Electronics'],
        price: '7300',
        offer: '150',
        offerPrice: '7150',
        color: ['black', 'white', 'gray'],
        condition: 'New'
    },
    {
        id: 6,
        title: `Apple iPad (6th Gen)`,
        details: `Imagine a world where a powerful yet compact device doubles up as almost everything you want it to be - a camera for capturing moments, a platform to complete work, a portal for entertainment, and above all a little something that you can rely on. Well folks, that's the world that awaits to be experienced with this iPad from Apple.`,
        category: ['Tablet', 'Electronics'],
        price: '80000',
        offer: '3000',
        offerPrice: '77000',
        color: ['black', 'black', 'gray'],
        condition: 'New'
    },
    {
        id: 7,
        title: `Analog Watch - For Men`,
        details: `Imagine a world where a powerful yet compact device doubles up as almost everything you want it to be - a camera for capturing moments, a platform to complete work, a portal for entertainment, and above all a little something that you can rely on. Well folks, that's the world that awaits to be experienced with this iPad from Apple.`,
        category: ['Watch', 'Electronics'],
        price: '2100',
        offer: '2050',
        offerPrice: '50',
        color: ['red', 'gray', 'orange'],
        condition: 'New'
    },
    {
        id: 8,
        title: `Apple Watch White Sport Band (GPS)`,
        details: `Barometric Altimeter, Heart Rate Sensor, Accelerometer, Gyroscope, Ambient Light Sensor, Built-in GPS and GLONASS`,
        category: ['Watch', 'Electronics'],
        price: '125000',
        offer: '8000',
        offerPrice: '117000',
        color: ['black', 'black', 'gray', 'blue'],
        condition: 'New'
    },
    {
        id: 9,
        title: `Apple iPhone X (Silver, 64 GB)`,
        details: `Meet the iPhone X - the device that's so smart that it responds to a tap, your voice, and even a glance. Elegantly designed with a large 14.73 cm (5.8) Super Retina screen and a durable front-and-back glass, this smartphone is designed to impress. What's more, you can charge this iPhone wirelessly.`,
        category: ['Phone', 'Electronics'],
        price: '125000',
        offer: '8000',
        offerPrice: '117000',
        color: ['black', 'black', 'gray', 'blue'],
        condition: 'New'
    },
    {
        id: 10,
        title: `iBall CompBook M500`,
        details: `Meet the iPhone X - the device that's so smart that it responds to a tap, your voice, and even a glance. Elegantly designed with a large 14.73 cm (5.8) Super Retina screen and a durable front-and-back glass, this smartphone is designed to impress. What's more, you can charge this iPhone wirelessly.`,
        category: ['Laptop', 'Electronics'],
        price: '25000',
        offer: '2000',
        offerPrice: '23000',
        color: ['black', 'black', 'gray', 'blue'],
        condition: 'New'
    },

    {
        id: 11,
        title: 'Steel Series Mouse',
        details: `Keep a tab on your daily activities with this tracker from GOQii. From your heart rate to your sleep patterns, this tracker helps you lead a healthy lifestyle by tracking your activities. You can also receive notifications from your phone on its large OLED display. Charging this device is easy, as it comes with an integrated USB charger, and it can run up to 7 days on a single full charge.`,
        category: ['Mouse', 'Electronics'],
        price: '1200',
        offer: '100',
        offerPrice: '1100',
        color: ['red', 'green', 'blue', 'yellow'],
        condition: 'New',
    },

    {
        id: 12,
        title: `boAt Rockerz 510 Super Extra Bass`,
        details: `Connect your smartphone to this headset using Bluetooth or a 3.5-mm auxiliary cable and get grooving. Packed with a 400-mAh battery, these Boat headphones offer a playback time of about 10 hours so that listening to your favourite tunes for hours on end is a piece of cake.`,
        category: ['Headphone', 'Electronics'],
        price: '2500',
        offer: '250',
        offerPrice: '2250',
        color: ['red', 'blue', 'yellow'],
        condition: 'New'
    },
    {
        id: 13,
        title: `Apple MacBook Air Core i5 8th Gen`,
        details: `The vision behind iMac has never wavered: Transform the desktop experience by fitting powerful, easy-to-use technology into an elegant, all-in-one design. The new iMac takes that idea to the next level — giving you even more amazing tools to do just about anything. iMac is packed with the latest processors, faster memory and phenomenal graphics. All coming to life on the brightest, most vibrant Retina display ever on a Mac. It’s the total package — powered up.`,
        category: ['Laptop', 'Electronics'],
        price: '120000',
        offer: '5000',
        offerPrice: '115000',
        color: ['gold', 'black', 'gray'],
        condition: 'New'
    },
    {
        id: 14,
        title: `Dragon War ELE-G11`,
        details: `Ergonomic Design for Professional Gamers to Give Extra Comfort, Braided Fiber Cable, Gold Plated USB Connector Provide Durability, Uses Sunplus Chipset, Customize the Devices Profile, Button Alignment, Performance and Speed, Capable of Pinpoint Tracking Precision Using Laser Beams of the Mouse and Attain Highest Scores in the Game, Can Use the Mouse on Any Surface without Any Performance Problems`,
        category: ['Mouse', 'Electronics'],
        price: '3200',
        offer: '500',
        offerPrice: '2700',
        color: ['gold', 'black', 'gray'],
        condition: 'New'
    },
    {
        id: 15,
        title: `Qwerty VR BOX Virtual Reality 3D Glasses`,
        details: `Good product!!!I am really happy with Flipkart!!!Soon i will review this amazing product on my channel and upload it(Search my channel named "R4Reviews" on youtube if you wanted to see my review).Thank you so much!!!`,
        category: ['Vr', 'Electronics'],
        price: '7300',
        offer: '150',
        offerPrice: '7150',
        color: ['black', 'white', 'gray'],
        condition: 'New'
    },
    {
        id: 16,
        title: `Apple iPad (6th Gen)`,
        details: `Imagine a world where a powerful yet compact device doubles up as almost everything you want it to be - a camera for capturing moments, a platform to complete work, a portal for entertainment, and above all a little something that you can rely on. Well folks, that's the world that awaits to be experienced with this iPad from Apple.`,
        category: ['Tablet', 'Electronics'],
        price: '80000',
        offer: '3000',
        offerPrice: '77000',
        color: ['black', 'black', 'gray'],
        condition: 'New'
    },
    {
        id: 17,
        title: `Analog Watch - For Men`,
        details: `Imagine a world where a powerful yet compact device doubles up as almost everything you want it to be - a camera for capturing moments, a platform to complete work, a portal for entertainment, and above all a little something that you can rely on. Well folks, that's the world that awaits to be experienced with this iPad from Apple.`,
        category: ['Watch', 'Electronics'],
        price: '2100',
        offer: '2050',
        offerPrice: '50',
        color: ['red', 'gray', 'orange'],
        condition: 'New'
    },
    {
        id: 18,
        title: `Apple Watch White Sport Band (GPS)`,
        details: `Barometric Altimeter, Heart Rate Sensor, Accelerometer, Gyroscope, Ambient Light Sensor, Built-in GPS and GLONASS`,
        category: ['Watch', 'Electronics'],
        price: '125000',
        offer: '8000',
        offerPrice: '117000',
        color: ['black', 'black', 'gray', 'blue'],
        condition: 'New'
    },
    {
        id: 19,
        title: `Apple iPhone X (Silver, 64 GB)`,
        details: `Meet the iPhone X - the device that's so smart that it responds to a tap, your voice, and even a glance. Elegantly designed with a large 14.73 cm (5.8) Super Retina screen and a durable front-and-back glass, this smartphone is designed to impress. What's more, you can charge this iPhone wirelessly.`,
        category: ['Phone', 'Electronics'],
        price: '125000',
        offer: '8000',
        offerPrice: '117000',
        color: ['black', 'black', 'gray', 'blue'],
        condition: 'New'
    },
    {
        id: 20,
        title: `iBall CompBook M500`,
        details: `Meet the iPhone X - the device that's so smart that it responds to a tap, your voice, and even a glance. Elegantly designed with a large 14.73 cm (5.8) Super Retina screen and a durable front-and-back glass, this smartphone is designed to impress. What's more, you can charge this iPhone wirelessly.`,
        category: ['Laptop', 'Electronics'],
        price: '25000',
        offer: '2000',
        offerPrice: '23000',
        color: ['black', 'black', 'gray', 'blue'],
        condition: 'New'
    },
];
